use_frameworks!

platform :ios, '9.0'

target 'STCommonComponent_Example' do
  pod 'STCommonComponent', :path => '../'

  target 'STCommonComponent_Tests' do
    inherit! :search_paths

    
  end
end
